name: Unpack ZIP to repo
on:
  push:           # запуск при любом пуше в main
    branches: [ "main" ]
  workflow_dispatch:  # ручной запуск из Actions

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate ZIP anywhere (root or one-level subfolders)
        id: locate
        shell: bash
        run: |
          set -e
          echo "Repo tree:"
          ls -la
          # ищем zip в корне или на 1 уровне подпапок
          ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
          if [ -z "$ZIP" ]; then
            ZIP=$(find . -maxdepth 2 -type f -name "*.zip" | head -n1 || true)
          fi
          if [ -z "$ZIP" ]; then
            echo "❌ ZIP not found. Upload a *.zip to repo root." >&2
            exit 1
          fi
          # убираем ./ префикс
          ZIP="${ZIP#./}"
          echo "ZIP_NAME=$ZIP" >> $GITHUB_OUTPUT
          echo "✅ Found ZIP: $ZIP"

      - name: Install unzip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip

      - name: Unpack and cleanup
        run: |
          set -e
          ZIP="${{ steps.locate.outputs.ZIP_NAME }}"
          echo "Unzipping: $ZIP"
          unzip -o "$ZIP" -d .
          rm -f "$ZIP"
          echo "After unzip:"
          ls -la

      - name: Commit unpacked files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: unpack ZIP via workflow"
            git push
          fi
